---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-ehr-opd-master
  name: csi-net-ehr-opd-master
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-ehr-opd-master
  type: ClusterIP
