---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-bm-invoice-ui
  name: csi-bm-invoice-ui
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-bm-invoice-ui
  type: ClusterIP
