---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-ehr-common-report-generator-java-sev
  name: csi-ehr-common-report-generator-java-sev
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ehr-common-report-generator-java-sev
  type: ClusterIP
