---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-noty-query
  name: csi-net-noty-query
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-noty-query
  type: ClusterIP
