apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
images:
- name: harbor.cs.local/vidaplus/bm-invoice-ui
  newTag: 4.2.175.0
kind: Kustomization
patchesStrategicMerge:
- replica-count.yaml
