---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-streaming-etl
  name: csi-streaming-etl
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-streaming-etl
  type: ClusterIP
