apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/csi-phr-base
  newTag: 4.0.22.331
