apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-java-ds-dental-core
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-java-ds-dental-core
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-java-ds-dental-core
        module: adt
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: active_profile
                  name: service-configs-adt
            - name: hostname
              value: csi-java-ds-dental-core
            - name: FEIGN_HYSTRIX_ENABLED
              value: 'false'
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
            - configMapRef:
                name: service-configs-adt
            - secretRef:
                name: service-adt-secret
          image: >-
            harbor.cs.local/vidaplus/csi-ds-dental-core-java-sev:V1.0.6
          imagePullPolicy: IfNotPresent
          name: csi-java-ds-dental-core
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
