---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-ds-dental-core
  name: csi-java-ds-dental-core
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-java-ds-dental-core
  type: ClusterIP
