apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ehr-config
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-ehr-config
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ehr-config
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: db-con-url
                  name: ehr-database-configs
            - name: SPRING_SECOND-DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: db-con-url-second
                  name: ehr-database-configs
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-con-username
                  name: ehr-database-secret
            - name: SPRING_SECOND-DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-con-username-second
                  name: ehr-database-secret
            - name: SPRING_JPA_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: SPRING_JPA_DATABASE-PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-con-password
                  name: ehr-database-secret
            - name: SPRING_SECOND-DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-con-password-second
                  name: ehr-database-secret
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: hostname
              value: csi-java-ehr-config
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
          image: 'harbor.cs.local/vidaplus/csi-ehr-config-java-sev:4.1.3.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1200
            timeoutSeconds: 10
          name: csi-ehr-config
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
