apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-rf-file-uploader
  namespace: csi-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-rf-file-uploader
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-rf-file-uploader
        module: reporting
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: SECURITY_IAM_URL
              value: 'https://csi-iam-service/'
            - name: hostname
              value: csi-reporting-service
          envFrom:
            - configMapRef:
                name: service-configs-rf-uploader
            - secretRef:
                name: service-secret-rf-uploader
          image: 'harbor.cs.local/vidaplus/csi-rf-file-uploader:4.0.1.9'
          imagePullPolicy: IfNotPresent
          name: csi-rf-file-uploader
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
