---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-rf-file-uploader-service
  name: csi-rf-file-uploader-service
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-rf-file-uploader
  type: ClusterIP
