apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
images:
- name: harbor.cs.local/vidaplus/csi-ehr-common-java-sev
  newTag: 4.1.93.0
kind: Kustomization
patchesStrategicMerge:
- replica-count.yaml
