apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-empiread
  namespace: csi-dev
spec:  
  replicas: 6
  selector:
    matchLabels:
      app: csi-net-empiread
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-empiread
        module: empi
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: harbor.cs.local/vidaplus/csi-empi-patient-service-read:4.2.5.0
          imagePullPolicy: IfNotPresent
          name: csi-net-empiread
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 512Mi
      imagePullSecrets:
        - name: regcred

