---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-workflow-automation
  name: csi-java-workflow-automation
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-workflow-automation
  type: ClusterIP
