apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-morgue-ui
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-morgue-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-morgue-ui
        module: rms
        tier: frontend
        track: stable
    spec:
      containers:
        - image: harbor.cs.local/vidaplus/morgue-ui:4.2.16.0
          imagePullPolicy: IfNotPresent
          name: csi-morgue-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 2m
              memory: 25Mi
      imagePullSecrets:
        - name: regcred
