apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-reporting
  namespace: csi-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-reporting
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-reporting
        module: reporting
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: kafka_bootstrap_servers
              valueFrom:
                configMapKeyRef:
                  key: CSI_LOGS_KAFKA_BOOTSTRAPADDRESS
                  name: service-configs
            - name: elk_log_topic
              valueFrom:
                configMapKeyRef:
                  key: CSI_LOGS_KAFKA_TOPIC
                  name: service-configs
            - name: SECURITY_IAM_URL
              value: 'https://csi-iam-service/'
            - name: hostname
              value: csi-reporting-service
          envFrom:
            - configMapRef:
                name: service-configs-reporting
            - secretRef:
                name: service-reporting-secret
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
          image: 'harbor.cs.local/vidaplus/csi-rf-reportingservice:4.1.7.1'
          imagePullPolicy: IfNotPresent
          name: csi-reporting
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - mountPath: /app/dbschema_config
              name: dbschema-config-vol
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: dbschema-config-vol
          projected:
            sources:
              - configMap:
                  name: service-configs-dbschemas-reporting
