---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-reporting
  name: csi-reporting
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-reporting
  type: ClusterIP
