apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
images:
- name: harbor.cs.local/vidaplus/csi-bm-billing-java-service
  newTag: 4.5.53.1-b
kind: Kustomization
patchesStrategicMerge:
- replica-count.yaml
