apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-approval-ui
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-approval-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-approval-ui
        module: billing
        tier: frontend
        track: stable
    spec:
      containers:
        - image: 'harbor.cs.local/vidaplus/approval-ui:4.3.109.0'
          imagePullPolicy: IfNotPresent
          name: csi-approval-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 2m
              memory: 25Mi
      imagePullSecrets:
        - name: regcred

