---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-erfuncti
  name: csi-net-erfuncti
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-erfuncti
  type: ClusterIP
