---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-pms-adt-request
  name: csi-pms-adt-request
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-pms-adt-request
  type: ClusterIP
