apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-noty-msgtempl
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-noty-msgtempl
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-noty-msgtempl
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: >-
            harbor.cs.local/vidaplus/csi-net-base-message-templates:4.0.5.0
          name: csi-net-noty-msgtempl
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred

