apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: csi-ehr-common-report-generator-java-sev
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 90