---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-base-utility
  name: csi-java-base-utility
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-base-utility
  type: ClusterIP
