apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-empiwrit
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-net-empiwrit
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-empiwrit
        module: empi
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: >-
            harbor.cs.local/vidaplus/csi-empi-patient-registration-srv:4.2.15.0
          name: csi-net-empiwrit
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 750Mi
      imagePullSecrets:
        - name: regcred

