---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-empiwrit
  name: csi-net-empiwrit
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-empiwrit
  type: ClusterIP
