---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-iam-service
  name: csi-iam-service
  namespace: csi-dev
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: csi-iam
  type: ClusterIP
