---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-net-empi-hijridte
  name: csi-net-empi-hijridte
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-net-empi-hijridte
  type: ClusterIP
