apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-mlm-ui
  namespace: csi-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-mlm-ui
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: csi-mlm-ui
        module: adt
        tier: frontend
        track: stable
    spec:
      containers:
        - image: harbor.cs.local/vidaplus/mlm-ui:4.4.100.0
          imagePullPolicy: IfNotPresent
          name: csi-mlm-ui
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 2m
              memory: 25Mi
      imagePullSecrets:
        - name: regcred
