apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-java-bb-service
  namespace: csi-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csi-java-bb-service
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-java-bb-service
        module: bloodbank
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: active_profile
                  name: service-config-bloodbank
            - name: apm_server
              valueFrom:
                configMapKeyRef:
                  key: apm_server
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: bloodbank-db-url
                  name: service-config-bloodbank
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: bloodbank-db-username
                  name: service-bloodbank-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: bloodbank-db-password
                  name: service-bloodbank-secret
            - name: SPRING_DATASOURCE_JPA_DATABASE_PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: bloodbank-db-platform
                  name: service-config-bloodbank
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: bootstrap-servers
                  name: service-config-pharmacy
            - name: ADT-DISCHARGE-START-NOTIFICATION_T
              valueFrom:
                configMapKeyRef:
                  key: discharge-start-notification
                  name: service-config-pharmacy
            - name: KAFKA_TOPIC_DISCHARGE-CLEAR-NOTIFICATION
              valueFrom:
                configMapKeyRef:
                  key: discharge-clear-notification
                  name: service-config-pharmacy
            - name: KAFKA_TOPIC_DISCHARGE-SUMMARY-CLEAR-NOTIFICATION
              valueFrom:
                configMapKeyRef:
                  key: discharge-summary-clear-notification
                  name: service-config-pharmacy
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: phrbase-client-id
                  name: service-pharmacy-secret
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: phrbase-client-secret
                  name: service-pharmacy-secret
            - name: hostname
              value: csi-java-bb-service
            - name: spring_jpa_show_sql
              value: 'true'
            - name: spring_jpa_show-sql
              value: 'true'
          image: harbor.cs.local/vidaplus/csi-java-bb-service:4.1.15.0
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
            initialDelaySeconds: 1200
            periodSeconds: 40
            timeoutSeconds: 30
          name: csi-java-bb-service
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 40
            timeoutSeconds: 30
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 1Gi
      imagePullSecrets:
        - name: regcred
