apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/bb-donation-srv
  newTag: 4.2.0.0-a1
