apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ehr-listener
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-ehr-listener
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ehr-listener
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: hostname
              value: csi-java-ehr-listener
          envFrom:
            - configMapRef:
                name: service-configs
          image: >-
            harbor.cs.local/vidaplus/csi-ehr-listener-java-sev:4.1.8.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1200
            periodSeconds: 40
            timeoutSeconds: 30
          name: csi-ehr-listener
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 40
            timeoutSeconds: 30
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
