apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/csi-empi-patient-service-read
  newTag: 4.2.4.0
