apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/bloodbank-ui
  newTag: 4.1.29.1
