---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-java-blood-transfusion
  name: csi-java-blood-transfusion
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-java-blood-transfusion
  type: ClusterIP
