apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-lab-scheduled
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-lab-scheduled
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-lab-scheduled
        module: lab
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: 'harbor.cs.local/vidaplus/lab-scheduled:4.0.18.0-a1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          name: csi-net-lab-scheduled
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
