apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ehr-or-anesthesia
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-ehr-or-anesthesia
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ehr-or-anesthesia
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: db-or-anes
                  name: ehr-database-configs
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-or-anesthesia-username
                  name: ehr-database-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-or-anesthesia-password
                  name: ehr-database-secret
            - name: SPRING_JPA_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: db-driver
                  name: service-configs
            - name: SPRING_JPA_DATABASE-PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: SPRING_JPA_HIBERNATE_DIALECT
                  name: service-configs
            - name: hostname
              value: csi-java-ehr-or-anesthesia
            - name: spring_liquibase_default_schema
              valueFrom:
                configMapKeyRef:
                  key: db-or-anesthesia-schema
                  name: ehr-database-configs
            - name: spring_liquibase_liquibase_schema
              valueFrom:
                configMapKeyRef:
                  key: db-or-anesthesia-schema
                  name: ehr-database-configs
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
          image: >-
            harbor.cs.local/vidaplus/csi-ehr-or-anesthesia-java-sev:4.1.38.0
          imagePullPolicy: IfNotPresent
          name: csi-ehr-or-anesthesia
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
