---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-rms-morgue
  name: csi-rms-morgue
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-rms-morgue
  type: ClusterIP
