apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-personalization
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-personalization
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-personalization
        module: base
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongo
            - name: SPRING_DATA_MONGODB_PORT
              value: '27017'
            - name: hostname
              value: csi-personalization-service
            - name: EUREKA_INSTANCE_HOSTNAME
              value: csi-personalization-service
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: security-service-configs
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-configs-secret
          image: >-
            harbor.cs.local/vidaplus/csi-personalization-service-java-sev:4.0.50.42
          name: csi-personalization
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 750Mi
      imagePullSecrets:
        - name: regcred

