---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-personalization
  name: csi-personalization
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-personalization
  type: ClusterIP
