apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-net-econsent
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-net-econsent
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: cs-net-econsent
        module: econsent
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: VERSION
              value: '4.1.2.0'
          envFrom:
            - configMapRef:
                name: econsent-service-configs
          image: 'harbor.cs.local/vidaplus/e-consent:4.1.2.0'
          imagePullPolicy: IfNotPresent
          name: cs-net-econsent
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 1Gi
      imagePullSecrets:
        - name: regcred
