---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cs-net-econsent
  name: cs-net-econsent
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cs-net-econsent
  type: ClusterIP
