---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: document-management-middleware
  name: document-management-middleware
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: document-management-middleware
  type: ClusterIP
