apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

patchesStrategicMerge:
- replica-count.yaml

images:
- name: harbor.cs.local/vidaplus/report-studio-ui
  newTag: 4.1.14.3
