apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-ehr-common
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-ehr-common
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-ehr-common
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: SPRING_KAFKA_CONSUMER_MAX_POLL_RECORDS
              value: '3'
            - name: SPRING_KAFKA_CONSUMER_MAX-POLL-RECORDS
              value: '3'
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: 'true'
            - name: active_profile
              valueFrom:
                configMapKeyRef:
                  key: activeProfile
                  name: service-configs
            - name: configserver
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: db-com-url
                  name: ehr-database-configs
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-com-username
                  name: ehr-database-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-com-password
                  name: ehr-database-secret
            - name: SPRING_JPA_DATABASE-PLATFORM
              valueFrom:
                configMapKeyRef:
                  key: SPRING_JPA_HIBERNATE_DIALECT
                  name: service-configs
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  key: db-driver
                  name: service-configs
            - name: HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  key: db-dialect
                  name: service-configs
            - name: hostname
              value: csi-java-ehr-common
          envFrom:
            - configMapRef:
                name: service-configs
          image: 'harbor.cs.local/vidaplus/csi-ehr-common-java-sev:4.1.54.0'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1200
            timeoutSeconds: 10
          name: csi-ehr-common
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 10
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
      imagePullSecrets:
        - name: regcred
