apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-ehr-opd-patient
  namespace: csi-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-net-ehr-opd-patient
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-ehr-opd-patient
        module: ehr
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: harbor.cs.local/vidaplus/csi-ehr-com-opd-patient-dotnet-sev:4.0.5.0
          imagePullPolicy: IfNotPresent
          name: csi-net-ehr-opd-patient
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 750Mi
      imagePullSecrets:
        - name: regcred

