apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-net-labsrvcs
  namespace: csi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-net-labsrvcs
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: csi-net-labsrvcs
        module: lab
        tier: backend
        track: stable
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: net_environment
                  name: service-configs
            - name: config_server
              valueFrom:
                configMapKeyRef:
                  key: config_server
                  name: service-configs
          image: 'harbor.cs.local/vidaplus/lab-labmgt-srv:4.1.266.0'
          imagePullPolicy: IfNotPresent
          name: csi-net-labsrvcs
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: 50m
              memory: 1Gi
      imagePullSecrets:
        - name: regcred
