---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-ehr-common-scheduler
  name: csi-ehr-common-scheduler
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-ehr-common-scheduler
  type: ClusterIP
