---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-bm-billing
  name: csi-bm-billing
  namespace: csi-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: csi-bm-billing-java-service
  type: ClusterIP
